version: '3.8'

services:
  api:
    build: ./api
    container_name: rinha-api
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - redis
      - kafka
    networks:
      - rinha-net

  redis:
    image: redis:7.2-alpine
    container_name: rinha-redis
    ports:
      - "6379:6379"
    networks:
      - rinha-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: rinha-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - rinha-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: rinha-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge 